name: game_of_life
description: An implementation of John Conway's Game of Life.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  flutter_state_notifier: ^1.0.0
  pausable_timer: ^2.0.0+1
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.7.0
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
